In [1]:
import pandas as pd
from pandas import DataFrame, Series

data_prac = pd.read_csv('총데이터/일별_모델데이터.csv', encoding = 'cp949')

In [2]:
# 학습 데이터 지정하기

X = data_prac.drop(columns=['PM2.5', 'PM10'], axis=1)
y = data_prac['PM10'] # 'PM2.5'

In [3]:
import numpy as np

print(X.shape)
print(y.shape)

(1491, 10)
(1491,)


In [4]:
import sklearn.model_selection as ms

X_train, X_test, y_train, y_test = ms.train_test_split(X, y, test_size = 0.2, random_state = 1)

In [9]:
import sklearn.neural_network as nn

pnn_clf = nn.MLPClassifier(learning_rate_init=0.001, max_iter=300, 
                           activation="relu", solver='adam', hidden_layer_sizes=(10, 10))
clf = pnn_clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

clf = nn.MLPClassifier(hidden_layer_sizes=(10,), activation='tanh', \
                    solver='adam', alpha=0.01, batch_size=32, \
                    learning_rate_init=0.1, max_iter=500)  # 객체 생성

In [10]:
import sklearn.metrics as mt
print("정확도:", mt.accuracy_score(y_test, y_pred))
print(mt.confusion_matrix(y_test, y_pred))

정확도: 0.013377926421404682
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [14]:
import tensorflow as tf
from tensorflow import keras
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np
from tensorflow.keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'

In [ ]:
model = Sequential()
model.add(Dense(input_dim=10, units=20, activation="relu")) #units ?? input_dim=10
model.add(Dense(units=15, activation="relu"))
model.add(Dense(units=10, activation="softmax"))

In [ ]:
model.compile(loss="categorical_crossentropy", 
              optimizer=Adam(learning_rate=0.001), metrics=['accuracy'])

In [ ]:
model.summary()

In [ ]:
hist = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=30, batch_size=100, verbose=2)
# 원래는 epoch를 더 크게 하는게 맞음

In [ ]:
loss, acc = model.evaluate(X_test, y_test)
print("loss=", loss)
print("accuracy=", acc)

In [ ]:
y_pred_class = model.predict_classes(X_test)

In [ ]:
y_test_class = np.argmax(y_test, axis=1)

In [ ]:
print(confusion_matrix(y_test_class, y_pred_class))

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(hist.hitory['accuracy'], color="blue", linestyle="--", label="train")
plt.plot(hist.history['val_accuracy'], color="red", label="validation")
plt.xlabel("epoch", fontsize=15)
plt.ylabel("accuracy", fontsize=15)
plt.title("ACCURACY", fontsize=18)
plt.legend(fontsize=15)
plt.grid(linestyle="--")

plt.subplot(1, 2, 2)
plt.plot(hist.hitory['loss'], color="blue", linestyle="--", label="train")
plt.plot(hist.history['val_loss'], color="red", label="validation")
plt.xlabel("epoch", fontsize=15)
plt.ylabel("loss", fontsize=15)
plt.title("LOSS", fontsize=18)
plt.legend(fontsize=15)
plt.grid(linestyle="--")